CREATE DATABASE CFT_DATABASE;
USE CFT_DATABASE;

CREATE TABLE USUARIO (
	CD_User INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    Usuario VARCHAR(50) NOT NULL,
    User_Email VARCHAR(120) NOT NULL UNIQUE,
    Password VARCHAR(255) NOT NULL,
    Estado TINYINT DEFAULT 1 NOT NULL,
    Fecha_create DATETIME DEFAULT CURRENT_TIMESTAMP,
    Fecha_Update DATETIME DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE CLIENTES (
	UserKey INT NOT NULL,
	CD_Client INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
	CL_name VARCHAR(50) NOT NULL,
    CL_descripcion VARCHAR(150),
    CL_estado INT NOT NULL,
    Fecha_create DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
    Fecha_Update DATETIME DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE ESTADO (
	Ky_Estado INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    Ky_Nombre VARCHAR(50) NOT NULL,
    estado TINYINT DEFAULT 1 NOT NULL
);

CREATE TABLE CATEGORIA (
	ID_CAT INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    Nombre VARCHAR(50) NOT NULL,
    estado TINYINT DEFAULT 1 NOT NULL
);

CREATE TABLE PRODUCTO (
    Categoria INT NOT NULL,
	KeyProduct INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    Nombre VARCHAR(80) NOT NULL,
    Descripcion VARCHAR(150),
    Precio DECIMAL(10,2) NOT NULL,
    Estado TINYINT DEFAULT 1 NOT NULL
);

CREATE TABLE PEDIDO (
	KyPedido INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    ClientKey INT NOT NULL,
    FechaPedido DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE DETALLE_PEDIDO (
	KyDetalle INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    PedidoKey INT NOT NULL,
    ProductKey INT NOT NULL,
    Cantidad INT NOT NULL,
    Precio_Unit DECIMAL(10,2) NOT NULL,
    SubTotal DECIMAL(10,2) NOT NULL
);