CREATE DATABASE CFT_DATABASE;
USE CFT_DATABASE;

CREATE TABLE USUARIO (
    usr_id INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    usr_nombre VARCHAR(50) NOT NULL,
    usr_email VARCHAR(120) NOT NULL UNIQUE,
    usr_password VARCHAR(255) NOT NULL,
    usr_estado TINYINT DEFAULT 1 NOT NULL,
    usr_fecha_creacion DATETIME DEFAULT CURRENT_TIMESTAMP,
    usr_fecha_actualizacion DATETIME DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE CLIENTES (
    cli_id INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    cli_usr_id INT NOT NULL,
    cli_nombre VARCHAR(50) NOT NULL,
    cli_descripcion VARCHAR(150),
    cli_estado_id INT NOT NULL,
    cli_fecha_creacion DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
    cli_fecha_actualizacion DATETIME DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP
);


CREATE TABLE ESTADO (
    est_id INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    est_nombre VARCHAR(50) NOT NULL,
    est_estado TINYINT DEFAULT 1 NOT NULL
);

CREATE TABLE CATEGORIA (
    cat_id INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    cat_nombre VARCHAR(50) NOT NULL,
    cat_estado TINYINT DEFAULT 1 NOT NULL
);

CREATE TABLE PRODUCTO (
    prod_id INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    prod_cat_id INT NOT NULL,
    prod_nombre VARCHAR(80) NOT NULL,
    prod_descripcion VARCHAR(150),
    prod_precio DECIMAL(10,2) NOT NULL,
    prod_estado TINYINT DEFAULT 1 NOT NULL
);

CREATE TABLE PEDIDO (
    ped_id INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    ped_cli_id INT NOT NULL,
    ped_fecha DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE DETALLE_PEDIDO (
    det_id INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    det_ped_id INT NOT NULL,
    det_prod_id INT NOT NULL,
    det_cantidad INT NOT NULL,
    det_precio_unitario DECIMAL(10,2) NOT NULL,
    det_subtotal DECIMAL(10,2) NOT NULL
);

CREATE TABLE PAGO (
    pago_id INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    pago_cli_id INT NOT NULL,
    pago_monto DECIMAL(10,2) NOT NULL,
    pago_fecha DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL
)